function augmenter = cifar10Augmenter()
% CIFAR typical: random translation (crop) + horizontal flip.
% Implement crop by random translation + fixed crop using output size fixed by augmentedImageDatastore.
augmenter = imageDataAugmenter( ...
    "RandXReflection", true, ...
    "RandXTranslation", [-4 4], ...
    "RandYTranslation", [-4 4]);
end
